apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: newsag

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
